### ISSUE TITLE
BRWAR samples have an incredibly low sample rate

### ISSUE THREAD

**Issue by cocoelacanth** [em-eight/mrst#6]
I'm currently trying to use MRST to convert the Fluidity soundtrack into a usable format.

I'm using the following command:
```
.\mrst extract Fluid.brsar --decode --extract-rwar
```
Folders 0 through 6 contain a `file.brwsd` file and a `wave.brwar` file. These extract and play just fine (they're just sound effects).

Folder 7 is a different story—rather than `file.brwsd`, it contains a `file.brbnk` file alongside the BRWAR. I suspect this folder contains the actual instruments for the game's music, which is stored in BRSEQ format in folders 8 through 33.

The trouble is, though, the WAV files I get when decoding the BRWAR in folder 7 are completely unrecognizable as the instruments that play in-game. Every sound is either just a low hum or completely silent.

If I decode the BRBNK file in folder 7 and open the resulting SF2 file in an editor like Polyphone, it reports that most samples have a sample rate of just 1368 Hz. That probably explains the inaudible sounds, but I'm not sure what's causing it or how to fix it.

Strangely, I've found that MRST will refuse to decode `file.brbnk` on its own:
```
>  .\mrst decode Fluid.brsar.d\_anonymous_group_\7\file.brbnk
"Fluid.brsar.d\\_anonymous_group_\\7\\file.brbnk" file format decode not supported
```
...but this doesn't happen if I use the `--decode` flag when extracting `Fluid.brsar`.

It also refuses to decode the BRSEQ files in folders 8 through 33; it complains about an "unknown MML command."
```
>  .\mrst decode Fluid.brsar.d\_anonymous_group_\8\file.brseq
Error: Unknown MML command 0xb0
```

**Comment by em-eight** [comment]
Hi CoCo, thank you for taking the time to describe the issue and sorry for the late reply

> Folder 7 is a different story—rather than `file.brwsd`, it contains a `file.brbnk` file alongside the BRWAR. I suspect this folder contains the actual instruments for the game's music, which is stored in BRSEQ format in folders 8 through 33.

That is correct, it is similar to an .sf2 file.

> The trouble is, though, the WAV files I get when decoding the BRWAR in folder 7 are completely unrecognizable as the instruments that play in-game. Every sound is either just a low hum or completely silent.
> 
> If I decode the BRBNK file in folder 7 and open the resulting SF2 file in an editor like Polyphone, it reports that most samples have a sample rate of just 1368 Hz. That probably explains the inaudible sounds, but I'm not sure what's causing it or how to fix it.
> 
> Strangely, I've found that MRST will refuse to decode `file.brbnk` on its own:
> 
> ```
> >  .\mrst decode Fluid.brsar.d\_anonymous_group_\7\file.brbnk
> "Fluid.brsar.d\\_anonymous_group_\\7\\file.brbnk" file format decode not supported
> ```

Hmm, it seems that the tool isn't parsing the file correctly. Can you send me the BRSAR at `m8em.eightm8@gmail.com`? I'll do tests and figure out what's wrong.

> ...but this doesn't happen if I use the `--decode` flag when extracting `Fluid.brsar`.
> 
> It also refuses to decode the BRSEQ files in folders 8 through 33; it complains about an "unknown MML command."
> 
> ```
> >  .\mrst decode Fluid.brsar.d\_anonymous_group_\8\file.brseq
> Error: Unknown MML command 0xb0
> ```

Yea, not all MML commands are supported yet. Again, send me the BRSAR and I'll try to add support to it.

BRSAR files tend to have slight quirks from version to version, so it's hard to provide support for them. If you can send the file to me, I'd be very happy. For now, maybe brawlcrate or VGMTrans (jasper's fork https://github.com/magcius/vgmtrans) can parse it? Those tools have their own shortcomings but who knows

**Comment by CocoTheMii** [comment]
> Hmm, it seems that the tool isn't parsing the file correctly. Can you send me the BRSAR at `m8em.eightm8@gmail.com`? I'll do tests and figure out what's wrong.

Sure thing, I've just sent an email.

> For now, maybe brawlcrate or VGMTrans (jasper's fork https://github.com/magcius/vgmtrans) can parse it? Those tools have their own shortcomings but who knows

Tried both with no luck, unfortunately. Brawlcrate seems to be able to open the file, but can't make much sense of its contents, and VGMTrans either crashes outright or just does nothing when I try to open the file.

**Comment by em-eight** [comment]
Long overdue, but I got to look at this more closely over the holidays.

1) I checked the sample rate manually, and as far as I know, it does seem to be very low in the original and not an mrst error. On polyphone though, I think all samples are audible, but low frequency hums. I guess this is not necessarily a parsing error because BRSEQs can do all sorts of weird post processing to make them sound normal. Let me know if you find a post processing that makes them normal, e.g. by speedup.
2) RBNK files not being able to be decoded by themselves in normal actually, I updated the readme so clarify that they can only be decoded while the whole BRSAR is extracted.
3) As afraid, I hadn't added the 0x80 command because it is not directly possible on MIDI. MIDI has a fixed PPQN, but Nintendo's MML allows dynamic time bases (perhaps related to the weird bassy samples?). To fix this we would need to compute a greatest common denominator of all timebases and then scale all intervals accordingly. This is quite a bit of undertaking, but you are welcome to do it.

I made an rc4 release where you can decode fluidity BRSEQs, but the MIDIs are completely off when you play them for now

**Comment by em-eight** [comment]
@cocoelacanth 
Never mind! I was handling the sampling rate pretty badly which caused issues with sampling rates higher than ~64kHz. The latest release now creates crystal clear Fluidity sample rips. The extracted BRSEQs also sound quite good.

**Comment by cocoelacanth** [comment]
That certainly helped! The music now sounds like music, which is a huge improvement.

Apologies for this very late reply, but I'm finding that the converted MIDIs still don't sound quite right. Some of the instruments sound rather choppy, and some notes are missing. Is this an issue you encountered as well?

**Comment by em-eight** [comment]
> That certainly helped! The music now sounds like music, which is a huge improvement.
> 
> Apologies for this very late reply, but I'm finding that the converted MIDIs still don't sound quite right. Some of the instruments sound rather choppy, and some notes are missing. Is this an issue you encountered as well?

Yeah, unfortunately the sequence format in wii games is not translatable to MIDI (it has more, unsupported features), so the converter just makes a best-effort conversion ignoring unsupported commands. I am not sure what's the solution for people just trying to rip the music, since as of now there is no PC BRSEQ player. I don't think there is a better way that to rip the wii/dolphin audio output directly. For people that want clean samples, the banks should at least be accurate and available for use in a DAW
